const fs=require('fs'),path=require('path'),root=__dirname;
const sales=JSON.parse(fs.readFileSync(path.join(root,'view_exports','export_Sales.json'),'utf8'));
const customers=JSON.parse(fs.readFileSync(path.join(root,'view_exports','export_Customer.json'),'utf8'));
const clean=v=>String(v??'').replace(/\u00a0/g,' ').trim();
const names=new Map(customers.map(c=>[clean(c.cuscod),clean(c.cusnam)||clean(c.cuscod)]));
const asOf=new Date(),dayMs=86400000;
const bucketFor=days=>days<=0?'notDue':days<=30?'1-30':days<=60?'31-60':days<=90?'61-90':days<=180?'91-180':'over180';
const invoices=[];
for(const row of sales){const total=Number(row.netamt)||0,received=Number(row.rcvamt)||0,balance=Math.max(0,total-received);if(balance<=.01)continue;const code=clean(row.cuscod)||'ไม่ระบุ',due=new Date(row.duedat),days=Math.floor((asOf-due)/dayMs),year=clean(row.Year)||String(new Date(row.docdat).getFullYear());invoices.push({year,docnum:clean(row.docnum),docdat:clean(row.docdat),duedat:clean(row.duedat),code,customer:names.get(code)||code,total,received,balance,daysOverdue:Math.max(0,days),bucket:bucketFor(days)});}
const summarize=list=>{const customerMap=new Map();for(const i of list){const c=customerMap.get(i.code)||{code:i.code,customer:i.customer,outstanding:0,overdue:0,invoices:0,oldestDays:0,lastInvoice:''};c.outstanding+=i.balance;if(i.daysOverdue>0)c.overdue+=i.balance;c.invoices++;c.oldestDays=Math.max(c.oldestDays,i.daysOverdue);if(i.docdat>c.lastInvoice)c.lastInvoice=i.docdat;customerMap.set(i.code,c);}const customers=[...customerMap.values()].sort((a,b)=>b.overdue-a.overdue||b.outstanding-a.outstanding),buckets=['notDue','1-30','31-60','61-90','91-180','over180'].map(key=>{const rows=list.filter(i=>i.bucket===key);return {key,value:rows.reduce((s,i)=>s+i.balance,0),invoices:rows.length,customers:new Set(rows.map(i=>i.code)).size};});return {summary:{outstanding:list.reduce((s,i)=>s+i.balance,0),overdue:list.filter(i=>i.daysOverdue>0).reduce((s,i)=>s+i.balance,0),notDue:list.filter(i=>i.daysOverdue===0).reduce((s,i)=>s+i.balance,0),invoices:list.length,customers:customers.length,asOf:asOf.toISOString().slice(0,10)},buckets,customers,invoices:list.sort((a,b)=>b.daysOverdue-a.daysOverdue||b.balance-a.balance)};};
const result={all:summarize(invoices),years:{}};for(const year of [...new Set(invoices.map(i=>i.year))].sort())result.years[year]=summarize(invoices.filter(i=>i.year===year));
fs.writeFileSync(path.join(root,'receivable_analytics.js'),'window.RECEIVABLE_ANALYTICS='+JSON.stringify(result)+';','utf8');console.log(`Generated receivables for ${invoices.length} outstanding invoices.`);
